[package]
name = "drawmymap2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "drawmymap2_lib"

[dependencies]
bevy = "0.13.1"
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.115"
